name: first-WF
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: |
          echo "Welcome to GHA"
          echo "This is Line 1"
          echo "This is Line 2"
