name: first-WF
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: build-step
        run: echo "A demo build"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test-Phase
        run: echo"Testing APP"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy-App
        run: echo "Deployig app"
      
