name: test-WF
on:
  push:
    branches:
      - main
      - feature/test-demo
  pull_request:
    branches:
      - main
      - develop
jobs:
  Build:
    runs-on: ubuntu_latest
    steps:
      - name: Build App
        run: echo "Buildong an application"
    
      
